#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The DiamaneOS Project
"""Write the translated fingerprint footer strings from AOSP's own translations.

AOSP Settings names the fingerprint feature "Pixel Imprint" in two enrolment
footer strings (four product variants each). res/values/strings.xml replaces it
with AOSP's generic name, "Fingerprint Unlock", in English. For every other
locale this script takes Settings' own translation and applies the small edits
in fingerprint_strings.json, which swap the Pixel name for that locale's
translation of "Fingerprint Unlock" (Settings' private_space_fingerprint_title)
and adjust only the grammar that has to agree with it.

Usage: make_fingerprint_strings.py SETTINGS_DIR RES_DIR
SETTINGS_DIR is a packages/apps/Settings checkout; RES_DIR is this overlay's res.
It fails if an edit no longer matches or a locale still names Pixel Imprint, so
rerun it after each GrapheneOS update and review what changed.
"""
import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

NAMES = ['security_settings_fingerprint_v2_enroll_introduction_footer_message_3',
         'security_settings_fingerprint_v2_enroll_introduction_footer_message_consent_3']
SKIP = {'en-rXC'}  # pseudo-locale generated from English, for developers only
LEFTOVER = re.compile(r'pixel|imprint|ଇମପ୍ରିଣ୍ଟ', re.I)
HEADER = '''<?xml version="1.0" encoding="utf-8"?>
<!--
     SPDX-License-Identifier: Apache-2.0
     Copyright 2026 The DiamaneOS Project
     Generated by make_fingerprint_strings.py from AOSP packages/apps/Settings
     res-product/values-{locale}/strings.xml; do not edit by hand.
-->
<resources>
'''


def stock_strings(xml):
    """Return [(name, product, raw)] for NAMES, keeping the raw XML text."""
    found = []
    for name in NAMES:
        pattern = r'<string name="%s"([^>]*)>(.*?)</string>' % re.escape(name)
        for attrs, raw in re.findall(pattern, xml, re.S):
            product = re.search(r'product="([^"]*)"', attrs)
            found.append((name, product.group(1) if product else None, raw))
    return found


def key(name, product):
    return name.rsplit('introduction_', 1)[1] + ':' + product


def check(locale, name, product, text):
    where = f'{locale} {key(name, product)}'
    problems = []
    if LEFTOVER.search(text):
        problems.append(f'{where}: still names Pixel Imprint')
    quoted = len(text) >= 2 and text.startswith('"') and text.endswith('"')
    inner = text[1:-1] if quoted else text
    if re.search(r'(?<!\\)"', inner):
        problems.append(f'{where}: unescaped double quote')
    if not quoted and re.search(r"(?<!\\)'", inner):
        problems.append(f'{where}: unescaped apostrophe')
    try:
        ET.fromstring(f'<string>{text}</string>')
    except ET.ParseError as error:
        problems.append(f'{where}: not well-formed XML: {error}')
    return problems


def main(settings_dir, res_dir):
    edits = json.loads((Path(__file__).parent / 'fingerprint_strings.json').read_text(encoding='utf-8'))
    problems, written = [], 0
    stock_locales = set()
    for path in sorted(Path(settings_dir, 'res-product').glob('values-*/strings.xml')):
        locale = path.parent.name[len('values-'):]
        strings = stock_strings(path.read_text(encoding='utf-8'))
        if not strings or locale in SKIP:
            continue
        stock_locales.add(locale)
        if locale not in edits:
            problems.append(f'{locale}: AOSP translates the strings but there are no edits')
            continue
        rules = edits[locale]['edits']
        used = [0] * len(rules)
        lines = []
        for name, product, text in strings:
            original = text
            for i, rule in enumerate(rules):
                scope = rule.get('applies_to', 'all')
                if (scope == 'all' or key(name, product) in scope) and rule['old'] in text:
                    text = text.replace(rule['old'], rule['new'])
                    used[i] += 1
            if text == original:
                problems.append(f'{locale} {key(name, product)}: no edit applied')
            problems += check(locale, name, product, text)
            lines.append(f'    <string name="{name}" product="{product}">{text}</string>\n')
        problems += [f'{locale}: edit {i} no longer matches: {rules[i]["old"]!r}'
                     for i, n in enumerate(used) if not n]
        out = Path(res_dir, f'values-{locale}', 'strings.xml')
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(HEADER.format(locale=locale) + ''.join(lines) + '</resources>\n', encoding='utf-8')
        written += 1
    problems += [f'{locale}: edits for a locale AOSP does not translate' for locale in sorted(set(edits) - stock_locales)]
    for problem in problems:
        print(problem, file=sys.stderr)
    print(f'{written} locales written, {len(problems)} problem(s)')
    return 1 if problems else 0


if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    sys.exit(main(sys.argv[1], sys.argv[2]))
